"""Add is_billable field to workloads

Revision ID: a94aa19e97c8
Revises: 467f9d41a818
Create Date: 2025-08-05 20:18:07.521319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94aa19e97c8'
down_revision: Union[str, Sequence[str], None] = '467f9d41a818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workloads', sa.Column('is_billable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workloads', 'is_billable')
    # ### end Alembic commands ###
